services:
  backend:
    container_name: backend_app 
    build: ./backend
    depends_on:
      - database 
    ports:
      - "5000:5000"
    networks:
      - app_network
    environment:
      MONGO_URI: ${MONGO_URI}
      MONGO_DB_NAME: ${MONGO_DB_NAME}
      API_FOOTBALL_KEY: ${API_FOOTBALL_KEY}

  frontend:
    container_name: frontend_app 
    build: ./frontend
    depends_on:
      - database
    ports:
      - "3000:80"
    networks:
      - app_network
    environment:
      VITE_API_URL: http://backend_app:5000 
  
  database:
    container_name: mongo_database 
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - fstats_database_volumes:/data/db 
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    networks:
      - app_network

volumes:
  fstats_database_volumes: {} 
networks:
  app_network:
    driver: bridge
